config/routes.rb
Rails.application.routes.draw do
  get 'courses/index'

  get 'hello' => 'greeter#hello'

  get 'goodbye' => 'greeter#goodbye'

  root 'greeter#hello'

end

app/models/coursera.rb
class Coursera
  include HTTParty
  base_uri 'https://api.coursera.org/api/catalog.v1/courses'
  default_params fields: "smallIcon,shortDescription", q: "search"
  format :json
  def self.for term
    get("", query: { query: term})["elements"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @search_term = params[:looking_for] || 'jhu'
    @courses = Coursera.for(@search_term)
  end
end

app/controllers/greeter_controller.rb
class GreeterController < ApplicationController
  def hello
    random_names = ["Alex", "Troll", "Michael"]
    @name = random_names.sample
    @time  = Time.now
    @times_display ||= 0
    @times_display += 1
  end

  def goodbye
    random_names = ["Alex", "Joe", "Michael"]
    @name = random_names.sample
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/greeter_helper.rb
module GreeterHelper
  def formatted_time(time)
    time.strftime("%I:%M%p")
  end
end

app/views/courses/index.html.erb
<h1>Searching for - <%= @search_term %></h1>
<form method="get">
  <label for="search"></label>
  <input type="text" name="looking_for" id="search"><br/>
  <input type="submit">
</form>
<br/>
<table border="1">
  <tr>
    <th>Image</th>
    <th>Name</th>
    <th>Description</th>
  </tr>
  <% @courses.each do |course| %>
      <tr class=<%= cycle('even', 'odd') %>>
        <td><%= image_tag(course["smallIcon"])%></td>
        <td><%= course["name"] %></td>
        <td><%= course["shortDescription"] %></td>
      </tr>
  <% end %>
</table>

app/views/greeter/goodbye.html.erb
<h1>Goodbye, <%= @name %></h1>
<%= Time.now %>

app/views/greeter/hello.html.erb
<h1>Hello, <%= @name %></h1>
<p>Time is <%= formatted_time(@time) %></p>
<p>This page has been visited <%= @times_display %> time(s)</p>
<p><%= link_to "Google", "https://google.com"%></p>
<p><%= link_to "Goodbye", goodbye_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Example</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>